name: pokery
description: Application for querying information about Pokemons.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: 3.2.3
  flutter:
    sdk: flutter
  flutter_svg: 2.0.3
  get_it: 7.2.0
  go_router: 6.2.0
  http: 0.13.5
  json_annotation: 4.8.0
  result_dart: 1.0.5

dev_dependencies:
  build_runner: 2.3.3
  flutter_launcher_icons: 0.12.0
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 6.6.1
  mocktail: 0.3.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/svgs/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter/Inter-VariableFont.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-Thin.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-ExtraLight.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-Light.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-Regular.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-Medium.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-SemiBold.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-Bold.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-ExtraBold.ttf
        # - asset: lib/assets/fonts/Inter/static/Inter-Black.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/pokeball.png"
  web:
    generate: true
    image_path: "lib/assets/images/pokeball.png"
  windows:
    generate: false
